# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: github-actions
  directory: ".github/workflows/"
  groups:
    External-Dependencies:
      applies-to: version-updates
      dependency-type: "production"
  schedule:
    interval: weekly
  ignore:
    - dependency-name: "microsoft/AL-Go-Actions/*"
    - dependency-name: "microsoft/AL-Go/*"
  labels:
    - "Automation"
  
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  allow:
    - dependency-type: "all"
  groups:
    NuGet-Dependencies:
      applies-to: version-updates
      dependency-type: "all"
  labels:
    - "Automation"