name: 'PowerShell'

on:
  push:
    branches: [ "main", "releases/*" ]
    paths: ["**.ps1", "**.psm1", "**.psd1", ".github/workflows/powershell.yaml" ]
  pull_request:
    branches: [ "main", "releases/*" ]
    paths: ["**.ps1", "**.psm1", "**.psd1", ".github/workflows/powershell.yaml" ]

permissions:
  contents: read

jobs:
  PSScriptAnalyzer:
    # https://github.com/microsoft/psscriptanalyzer-action
    # For more information on PSScriptAnalyzer in general, see
    # https://github.com/PowerShell/PSScriptAnalyzer
    name: Run PSScriptAnalyzer
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f # v1.1
        with:
          path: .\
          recurse: true
          excludeRule: '"PSAvoidUsingInvokeExpression", "PSUseShouldProcessForStateChangingFunctions", "PSAvoidUsingWriteHost", "PSAvoidUsingCmdletAliases", "PSUseSingularNouns", "PSUseApprovedVerbs"'
          output: results.sarif

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@d88a5540c3fd916f4e15b7744d287a124278e065 # v3.30.8
        with:
          sarif_file: results.sarif

  RunTests:
    name: Run PS Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run PS Tests
        run: |
          . (Join-Path "." "build/scripts/tests/runTests.ps1")
