name: Scorecard analysis
on:
  workflow_dispatch:
  schedule:
    # Weekly on Monday at 08:00 UTC
    - cron: "0 8 * * 1"

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    if: github.repository_owner == 'microsoft'
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Needed for Code scanning upload
      id-token: write # Needed for GitHub OIDC token if publish_results is true

    steps:
      - name: "Checkout code"
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@f779452ac5af1c261dce0346a8f964149f49322b # v2.16.4
        with:
          sarif_file: results.sarif
