name: 'Verify App Changes'

on:
  pull_request:
    branches: [ 'main', 'releases/*']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  VerifyAppChanges:
    runs-on: windows-latest
    name: Verify App Changes
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.sha }}

      - uses: microsoft/BCApps/.github/actions/TestPreprocessorSymbols@main

      - uses: microsoft/BCApps/.github/actions/TestObjectIdsAndManifests@main
