name: 'Verify App Changes'

on:
  pull_request:
    branches: [ 'main', 'releases/*']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  VerifyAppChanges:
    runs-on: windows-latest
    name: Verify App Changes
    steps:
      - name: checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.sha }}

      - uses: microsoft/BCApps/.github/actions/TestPreprocessorSymbols@main

      - uses: microsoft/BCApps/.github/actions/TestObjectIdsAndManifests@main
